### ISSUE TITLE
desktop: quiz title margin (or highlight?)

### ISSUE THREAD

**Issue by diachedelic** [Stjep1/DECO1016#6]
Is the green box supposed to be a highlight for the title, or is there meant to be more vertical margin?

https://stjep1.github.io/DECO1016/quiz.html

![image](https://user-images.githubusercontent.com/310464/48179849-36827c00-e375-11e8-9c71-d2686fbfe87d.png)

**Comment by Stjep1** [comment]
This is part of the z-index issue

**Comment by diachedelic** [comment]
Duplicate of #9
